language: java

jdk:
  - oraclejdk8

install:
  - git clone https://github.com/judgels/judgels.git ../judgels
  - git clone https://github.com/judgels/commons.git ../commons
  - git clone https://github.com/judgels/sealtiel-commons.git ../sealtiel-commons
  - git clone https://github.com/judgels/play-commons.git ../play-commons

script:
  - ../judgels/scripts/download-activator.sh
  - ../judgels/scripts/download-checkstyle.sh
  - export PATH=$PATH:~/activator
  - activator test
  - activator checkstyle
