language: java

jdk:
  - oraclejdk8

install:
  - git clone https://github.com/judgels/commons.git ../commons
  - git clone https://github.com/judgels/sealtielcommons.git ../sealtielcommons
  - git clone https://github.com/judgels/playcommons.git ../playcommons

script:
  - ./activator test
